version: '3'

services:
#  database:
#    build:
#      context: ./database
#    environment:
#      - MYSQL_DATABASE=${DATABASE_NAME}
#      - MYSQL_USER=${DATABASE_USER}
#      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./database/data:/var/lib/mysql


  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA={PGDATA}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    networks:
      - postgres_network

  php-fpm:
    build:
      context: ./php-fpm
    depends_on:
      #      - database
      - postgres
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
    volumes:
      - ../src:/var/www

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

networks:
  postgres_network:
    driver: bridge
volumes:
  pgadmin-data: